Replace random art tab with critique tab
Weasyl/weasyl pull request #1105
Opened 2021-08-11 06:25 UTC by charmander

Because when have you ever wanted to see 11 random submissions out of the last 256?

- corrects searching within browse categories
- allows browsing critique requests in chronological order
- splits index cache
- redesigns stream and site update sections based on weasyl2014
- fixes comment hiding on site updates
- makes narrow viewport design use home tabs instead of expandable sections (I fixed section closing and state indication first, but then this was better)
- makes thumbnail layout algorithm do what was originally intended
- removes unnecessarily large padding from thumbnail grids when JavaScript hasn’t run [yet]
- reduces recent submissions on homepage to medium footprint (two rows at max width) and removes their heading to place tabs and part of recently popular above the fold on many common viewport sizes
- limits homepage critique selection to one per person
- allows critique thumbnails to use consistently-sized and WebP thumbnails (plus any future changes)
- probably more

Sorry this is so entangled.

2021-08-12 00:15 UTC, kfkitsune requested changes
One thing that needs to be fixed, one thing that might not have been introduced here (and just a byproduct of the dev DB being a partial export), and one being an amusing observation of GitHub deciding to have a negative-one and zeroth lines in a diff? (See Gitter/Matrix for the screencapture.)

2021-08-12 00:59 UTC, charmander commented on weasyl/controllers/general.py
> +}
Browse Users isn’t a thing (current https://www.weasyl.com/search?find=user is submissions), but yes, this should be fixed. Thanks!

2021-08-12 01:01 UTC, charmander commented on weasyl/templates/admincontrol/siteupdate.html
> +      <input type="checkbox" name="wesley"$:{' checked' if update['wesley'] else ''}>
Yep, that’s exactly what it is. Pick your favorite existing user id, edit `config/weasyl-staff.example.py`, run `./wzl configure`.

```python
wesley = 34165
```

2021-08-13 00:59 UTC, kfkitsune approved these changes
As far as I can tell, it looks good to me!

2021-08-13 05:21 UTC, charmander commented
Thank you for the review!

2021-08-13 05:46 UTC, merged