Submission settings columns
Weasyl/weasyl pull request #229
Opened 2017-04-03 02:45 UTC by hyena

These changes affect a lot of logic so it needs a careful once over. I've tested some of these but it could benefit from other people pocking too:

Make sure that you can't view hidden submissions (checked)
Can't view friends-only submissions without being friends (checked briefly)
Critique shows up correctly (checked)
Friends-only shows up in read (checked)
Moderation tools work (checked somewhat)

2017-04-03 02:48 UTC, hyena commented on weasyl/moderation.py
> +    # TODO(hyena): su.settings has been removed from here. Replace it with the individual columns and fix up
Note to self: You've done this; remove the comment.

2017-04-13 22:23 UTC, charmander commented on weasyl/errorcode.py
> +    # TODO(hyena): The pointer on this could be more explicit. HOW should the user report the bug? To WHOM?
This comment appears to go with `logicalError`.

2017-04-13 22:25 UTC, charmander commented on weasyl/moderation.py
> +                .where(tbl.c.hidden.isnot(True)))
Does this work as `.where(~tbl.c.hidden)`?

2021-07-24 05:31 UTC, charmander requested changes
To check:

- `is_hidden` in weasyl/templates/modcontrol/reports.html

2021-07-24 05:31 UTC, charmander commented on weasyl/favorite.py
> -    elif "f" in query[1] and not frienduser.check(userid, query[0]):
Not introduced in this PR, but a reminder for after: there should probably be a check for `hidden`.

2021-07-24 05:31 UTC, charmander commented on weasyl/favorite.py
> +        query = d.execute("SELECT userid, friends_only FROM %s WHERE %s = %i",
Branch can be simplified.

2021-07-24 05:31 UTC, charmander commented on weasyl/favorite.py
> +    elif (submitid and query[1] or not submitid and "f" in query[1]) and not frienduser.check(userid, query[0]):
Selecting `settings ~ 'f'` would avoid this.

2021-07-24 05:31 UTC, charmander commented on libweasyl/libweasyl/alembic/versions/30ddd5fc6d26_submission_settings_columns.py
> +        sa.Column('embed_type', embed_types, nullable='f'),
`nullable='f'`?

2021-07-24 05:33 UTC, charmander commented on weasyl/submission.py
(no longer exists)

2021-07-24 08:40 UTC, charmander approved these changes

2021-07-25 09:22 UTC, merged